spring.application.name=goi-mon-an
server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=goi_y_mon_an;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Thymeleaf (HTML/CSS/JS frontend)
spring.thymeleaf.cache=false

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
